[tool.poetry]
name = "pyphocorehelpers"
version = "0.0.2"
description = "A collection of generally useful python code by Pho Hale"
authors = ["Pho Hale <CommanderPho@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
objsize = "^0.6.1"
indexed = "^1.3.0"
PyQt5Singleton = "^0.1"
h5py = "^3.8.0"
QtPy = "^2.1.0"
PyQt5-sip = "^12.11.1"
numpy = "^1.23.2"
pandas = "^1.5.1"
modin = {version = "^0.18.1", extras = ["all"]} # used to accelerate pandas
ansi2html = "^1.8.0"
numba = "^0.56.4"

[tool.poetry.group.dev.dependencies]
importlib-metadata = "^6.0.0"


[tool.poetry.group.viz.dependencies]
pyvista = "^0.38.0"
matplotlib = "^3.6.3"
vedo = "^2023.4.3"
hdf5plugin = "^4.1.1"
silx = "^1.1.2"
vtk = "^9.2.5"

# [tool.poetry.group.remote.dependencies]
# neuropy = {git = "https://github.com/CommanderPho/NeuroPy.git"} # , rev = "main", extras = ["acceleration"]

[tool.poetry.group.local.dependencies]
neuropy = {path = "../NeuroPy", develop=true} # , rev = "main", extras = ["acceleration"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
