[tool.poetry]
name = "pyphocorehelpers"
version = "0.2.0"
description = "A collection of generally useful python code by Pho Hale"
authors = ["Pho Hale <CommanderPho@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
objsize = "^0.6.1"
indexed = "^1.3.0"
h5py = "^3.8.0"
numpy = "^1.23.2"
pandas = "^1.5.1"
ansi2html = "^1.8.0"
handsdown = "^2.0.1"

[tool.poetry.group.dev.dependencies]
importlib-metadata = "^6.0.0"

[tool.poetry.group.accel.dependencies]
numba = {version = "^0.56.4", optional = true}

[tool.poetry.group.viz.dependencies]
pyvista = "^0.38.0"
matplotlib = "^3.6.3"
vedo = "^2023.4.3"
hdf5plugin = "^4.1.1"
silx = "^1.1.2"
vtk = "^9.2.5"
PyQt5Singleton = { version = "^0.1", optional = true}
QtPy = { version = "^2.1.0", optional = true}
PyQt5-sip = { version = "^12.11.1", optional = true}

[tool.poetry.group.remote.dependencies]
neuropy = {path = "../NeuroPy", develop=true}

[tool.poetry.extras]
accel = ["numba"]
vizqt = ["PyQt5Singleton", "QtPy", "PyQt5-sip"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
