"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import List, Optional, Tuple, Union
from numpy.typing import NDArray
from pathlib import Path
from PIL import Image
from plotly.graph_objects import Figure as PlotlyFigure
from matplotlib.figure import FigureBase

def add_border(image: Image.Image, border_size: int = ..., border_color: tuple = ...) -> Image.Image:
    ...

def add_shadow(image: Image.Image, offset: int = ..., background_color: tuple = ..., shadow_color: tuple = ...) -> Image.Image:
    ...

def img_data_to_greyscale(img_data: NDArray) -> NDArray[np.uint8]:
    """ rescales the img_data array to 0-255 
    
    from pyphocorehelpers.plotting.media_output_helpers import img_data_to_greyscale
    
    norm_array = img_data_to_greyscale(img_data)
    
    """
    ...

def get_array_as_image(img_data, desired_width: Optional[int] = ..., desired_height: Optional[int] = ..., colormap=..., skip_img_normalization: bool = ..., export_grayscale: bool = ...) -> Image.Image:
    """ Like `save_array_as_image` except it skips the saving to disk. Converts a numpy array to file as a colormapped image
    
    # Usage:
    
        from pyphocorehelpers.plotting.media_output_helpers import get_array_as_image
    
        image = get_array_as_image(img_data, desired_height=100, desired_width=None, skip_img_normalization=True)
        image
                
    """
    ...

def save_array_as_image(img_data, desired_width: Optional[int] = ..., desired_height: Optional[int] = ..., colormap=..., skip_img_normalization: bool = ..., out_path=..., export_grayscale: bool = ...) -> Tuple[Image.Image, Path]:
    """ Exports a numpy array to file as a colormapped image
    
    # Usage:
    
        from pyphocorehelpers.plotting.media_output_helpers import save_array_as_image
    
        image, out_path = save_array_as_image(img_data, desired_height=100, desired_width=None, skip_img_normalization=True)
        image
                
    """
    ...

def get_array_as_image_stack(imgs: List[Image.Image], offset=..., single_image_alpha_level: float = ..., should_add_border: bool = ..., border_size: int = ..., border_color: Tuple[int, int, int] = ..., should_add_shadow: bool = ..., shadow_offset: int = ..., shadow_color: Tuple[int, int, int, int] = ...) -> Image.Image:
    """ Handles 3D images
    Given a list of equally sized figures, how do I overlay them in a neat looking stack and produce an output graphic from that?
    I want them offset slightly from each other to make a visually appealing stack

    single_image_alpha_level = 0.5 - adjust this value to set the desired transparency level (0.0 to 1.0)
    offset = 10  # your desired offset

    2024-01-12 - works well

    Usage:
        from pyphocorehelpers.plotting.media_output_helpers import get_array_as_image_stack, save_array_as_image_stack

        # Let's assume you have a list of images
        images = ['image1.png', 'image2.png', 'image3.png']  # replace this with actual paths to your images
        output_img, output_path = render_image_stack(out_figs_paths, offset=55, single_image_alpha_level=0.85)

    """
    ...

def save_array_as_image_stack(images: List[Path], offset=..., single_image_alpha_level: float = ...): # -> tuple[Image, Path]:
    """ 
    Given a list of equally sized figures, how do I overlay them in a neat looking stack and produce an output graphic from that?
    I want them offset slightly from each other to make a visually appealing stack


    single_image_alpha_level = 0.5 - adjust this value to set the desired transparency level (0.0 to 1.0)
    offset = 10  # your desired offset

    2024-01-12 - works well

    Usage:
        from pyphocorehelpers.plotting.media_output_helpers import save_array_as_image_stack

        # Let's assume you have a list of images
        images = ['image1.png', 'image2.png', 'image3.png']  # replace this with actual paths to your images
        output_img, output_path = render_image_stack(out_figs_paths, offset=55, single_image_alpha_level=0.85)

    """
    ...

def save_array_as_video(array, video_filename=..., fps=..., isColor=..., colormap=..., skip_img_normalization=..., debug_print=..., progress_print=...): # -> Path:
    """
    Save a 3D numpy array as a grayscale video.

    NOTE: .avi is MUCH faster than .mp4, by like 100x or more!
    
    Parameters:
    - array: numpy array of shape (timesteps, height, width)
    - output_filename: name of the output video file
    - fps: frames per second for the output video


    Usage:

        from pyphocorehelpers.plotting.media_output_helpers import save_array_as_video
        
        video_out_path = save_array_as_video(array=active_relative_entropy_results['snapshot_occupancy_weighted_tuning_maps'], video_filename='output/videos/snapshot_occupancy_weighted_tuning_maps.avi', isColor=False)
        print(f'video_out_path: {video_out_path}')
        reveal_in_system_file_manager(video_out_path)
    """
    ...

def colormap_and_save_as_video(array, video_filename=..., fps=..., colormap=...): # -> Path:
    ...

def create_video_from_images(image_folder: str, output_video_file: str, seconds_per_frame: float, frame_size: tuple = ..., codec: str = ...) -> Path:
    """ 
    Loads sequence of images from a folder and joins them into a video where each frame is a fixed duration (`seconds_per_frame`)
    
    # Usage:
        from pyphocorehelpers.plotting.media_output_helpers import create_video_from_images
        from pyphoplacecellanalysis.GUI.Napari.napari_helpers import napari_export_image_sequence
        ## Save images from napari to disk:
        desired_save_parent_path = Path('2024-08-08 - TransitionMatrix/PosteriorPredictions').resolve()
        imageseries_output_directory = napari_export_image_sequence(viewer=viewer, imageseries_output_directory=desired_save_parent_path, slider_axis_IDX=0)
        ## Build video from saved images:
        video_out_file = desired_save_parent_path.joinpath('output_video.mp4')
        create_video_from_images(image_folder=imageseries_output_directory, output_video_file=video_out_file, seconds_per_frame=0.2)

    """
    ...

def create_gif_from_images(image_folder: str, output_video_file: str, seconds_per_frame: float) -> Path:
    """ 
    Loads sequence of images from a folder and joins them into an animated GIF where each frame is a fixed duration (`seconds_per_frame`)
    
    # Usage:
        from pyphocorehelpers.plotting.media_output_helpers import create_gif_from_images
        from pyphoplacecellanalysis.GUI.Napari.napari_helpers import napari_export_image_sequence
        ## Save images from napari to disk:
        desired_save_parent_path = Path('2024-08-08 - TransitionMatrix/PosteriorPredictions').resolve()
        imageseries_output_directory = napari_export_image_sequence(viewer=viewer, imageseries_output_directory=desired_save_parent_path, slider_axis_IDX=0)
        ## Build animated .gif from saved images:
        gif_out_file = desired_save_parent_path.joinpath('output_video.gif')
        create_gif_from_images(image_folder=imageseries_output_directory, output_video_file=gif_out_file, seconds_per_frame=0.2)

    """
    ...

def fig_to_clipboard(a_fig: Union[PlotlyFigure, FigureBase], format=..., **kwargs): # -> None:
    """ Any common figure type (matplotlib, Plotly, etc) to clipboard as image  _______________________________________________________________________________________________  
    
    from pyphocorehelpers.plotting.media_output_helpers import fig_to_clipboard
    
    fig_to_clipboard(fig)

    """
    ...

