"""
This type stub file was generated by pyright.
"""

class Assert:
    """ Convenince assertion helpers that print out the value that causes the assertion along with a reasonable message instead of showing nothing
    
    
    from pyphocorehelpers.assertion_helpers import Assert
        
        
    """
    @classmethod
    def path_exists(cls, path): # -> None:
        """
        # Usage:
            Assert.path_exists(global_batch_result_inst_fr_file_path)
        """
        ...
    
    @classmethod
    def len_equals(cls, arr_or_list, required_length: int): # -> None:
        """ Ensures the length is equal to the required_length, if it fails, it prints the actual length
        """
        ...
    
    @classmethod
    def same_length(cls, *args): # -> None:
        """ Ensures all passed *args are the same length (according to len(...), if it fails, it prints the actual length of each arg.
        """
        ...
    


