"""
This type stub file was generated by pyright.
"""

class Assert:
	""" Convenince assertion helpers that print out the value that causes the assertion along with a reasonable message instead of showing nothing
	
	
	from pyphocorehelpers.assertion_helpers import Assert
		
		
	"""
	def path_exists(path): # -> None:
		"""
		# Usage:
			Assert.path_exists(global_batch_result_inst_fr_file_path)
		"""
		...
	
	def len_equals(arr_or_list, required_length: int): # -> None:
		""" Ensures the length is equal to the required_length, if it fails, it prints the actual length
		"""
		...
	


