"""
This type stub file was generated by pyright.
"""

from PIL import Image

def build_icon(baseIconPath, overlayIconPath, outputIconPath=..., should_defer_show: bool = ...) -> Image:
    """ 2022-10-04 - This builds a simple icon with an overlay icon. Not quite working because the overlay icon is rendering with a white background.
    
    from pyphocorehelpers.image_helpers import build_icon
    
    
    """
    ...

def build_icon_example_grid(icons_path=..., should_save: bool = ..., should_defer_show: bool = ...) -> Image:
    ...

