"""
This type stub file was generated by pyright.
"""

import ipykernel

"""

You can use `pd.describe_option()` to see the various customization options you can set for pandas

"""
def set_pho_preferences(is_concise=...): # -> None:
    """ Sets Pho Hale's general preferences for Jupyter Notebooks
    
    Includes increasing the number of rows/columns displayed for Pandas dataframes, and setting the numpy print options to be full-width for the jupyter notebook.
    """
    ...

def set_pho_preferences_verbose(): # -> None:
    ...

def set_pho_preferences_concise(): # -> None:
    ...

def set_pho_pandas_display_preferences(is_concise=...): # -> None:
    ...

def set_pho_numpy_display_preferences(is_concise=...): # -> None:
    ...

def array_repr_with_graphical_shape(ip: ipykernel.zmqshell.ZMQInteractiveShell) -> ipykernel.zmqshell.ZMQInteractiveShell:
    """Generate an HTML representation for a NumPy array, similar to Dask.
        
    from preferences_helpers import array_graphical_shape
    from pyphocorehelpers.print_helpers import array_preview_with_graphical_shape_repr_html
    
    # Register the custom display function for NumPy arrays
    import IPython
    
    ip: "ipykernel.zmqshell.ZMQInteractiveShell)" = IPython.get_ipython()


    """
    ...

def dataframe_show_more_button(ip: ipykernel.zmqshell.ZMQInteractiveShell) -> ipykernel.zmqshell.ZMQInteractiveShell:
    """Adds a functioning 'show more' button below each displayed dataframe to show more rows.

    Usage:
        ip = get_ipython()
        ip = dataframe_show_more_button(ip=ip)
    """
    ...

