"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def set_pho_preferences(is_concise=...):
    """ Sets Pho Hale's general preferences for Jupyter Notebooks
    
    Includes increasing the number of rows/columns displayed for Pandas dataframes, and setting the numpy print options to be full-width for the jupyter notebook.
    """
    ...

def set_pho_preferences_verbose():
    ...

def set_pho_preferences_concise():
    ...

def set_pho_pandas_display_preferences(is_concise=...):
    ...

def set_pho_numpy_display_preferences(is_concise=...):
    ...

